# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: languagetool
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  languagetool:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-languagetool@v1.23.0
        with:
          patterns: README.txt
          language: en-US
          disabled_categories: TYPOS,TYPOGRAPHY
          disabled_rules: WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE,EN_COMPOUNDS_FAIL_SAFE,HYPHEN_TO_EN
